{% set name = "tableone" %}
{% set version = "0.9.5" %}
{% set sha256 = "dade3a7225c438a0ad1d7ea50b4752fc19550c1b09fa832f1cc9d655d903f70b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - setuptools

  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - scipy
    - statsmodels
    - tabulate

test:
  requires:
    - python {{ python_min }}
  imports:
    - tableone

about:
  home: http://github.com/tompollard/tableone
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create Table 1 for research papers in Python
  description: |
    tableone is a package for creating Table 1 for research papers
    in Python.
  doc_url: http://tableone.readthedocs.io/
  dev_url: https://github.com/tompollard/tableone

extra:
  recipe-maintainers:
    - tompollard
    - alistairewj
