{% set name = "tableone" %}
{% set version = "0.7.11" %}
{% set sha256 = "2793c3a55d54f22ed0156b7e56f9d3edb07dd4d010ea002747a65df65a3eac11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pandas
    - numpy
    - scipy
    - statsmodels
    - tabulate

test:
  imports:
    - tableone

about:
  home: http://github.com/tompollard/tableone
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create Table 1 for research papers in Python
  description: |
    tableone is a package for creating Table 1 for research papers
    in Python.
  doc_url: http://tableone.readthedocs.io/
  dev_url: https://github.com/tompollard/tableone

extra:
  recipe-maintainers:
    - tompollard
    - alistairewj
