{% set name = "tableone" %}
{% set version = "0.6.4" %}
{% set sha256 = "ad0a79ae8fd44f494be6836b4090cf2fad98e4c07bb65ca20d95482817dd976f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pandas
    - numpy
    - scipy
    - statsmodels
    - tabulate

test:
  imports:
    - tableone

about:
  home: http://github.com/tompollard/tableone
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Create Table 1 for research papers in Python'
  description: |
    tableone is a package for creating Table 1 for research papers
    in Python.
  doc_url: http://tableone.readthedocs.io/
  dev_url: https://github.com/tompollard/tableone

extra:
  recipe-maintainers:
    - tompollard
    - alistairewj
