travis:
  secure:
    BINSTAR_TOKEN: q89CbZ6YcMmaHmzu9yx8rCRqoHSkaQWzLWU0jIC+U4ihIKRjz4T7lINWbFD+GfiFt8f+qnbjX6EmLI/V6dz56MgiRY0ry9eluxHmReLaaGl9VxWsxB6ai7pTQaIDIGwG3FuPo6DBZtCeRp2AbYigY824ebukAIPR874dm5w0jSQSCb/N2i1prTrh5GyyfTbiSP0VSfsZPQjB1vgQuMpOzhxNLCc4opzvw/oxYS9eNvFGFQ+mkH6xabW4ZYf4vuNTJuBaHqRhArBjOdWBKeCYjZEbWRFhWWd7Dj+aq7Ad/Sb54N2m2B1dZ7+cUuZLBqb52nQd4Ye5SSSN+ytlJLiZK9oeLfNnhXWGarLA5CekHklu82neerBkvpJ7aucNtG7yWpD6NpHP2ScTHTyJMeLeHiipcfa6Af7OFtLT10fN6ZYKxgfNocekGkIe9wmTy23l/1paJYj6uLEbv2eVotfOL+a8Gbw6NXcZi1qywedpwN8tba6iPq4JwmghJnjcWkEBJrntShbcjk91wFp8bQrQbZrS+HuSZLhOljtzGw4YBhIfisVe+2BRpS1EdH0K2iKsC5zD6eCk1AmyN0EobANgQYUVU7zdXoxZxMzOhU5GoggJmmOQ7YgYxk4PtMAExThB0bce0LOWH1ddkz5G8dRILoNfgSQBrt/IJRrNBVqg50Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
