travis:
  secure:
    BINSTAR_TOKEN: aTnJHSBP/WOlmO/2sRv1Lj5ZwAEryMRsyhb1tNB5mzwAppp7PO7NYd7CYAlxwxOMAXlGr64ttwohXqrLdDIIsVh94UeriSVEWVbZCznwo2217QyzXjkY4iwJkCK09iZXVUlYGebi0mcDi4jekE4vEN1YQYgNWN6Bq1kKRzju+OEzK4pWfFluY6SFzGvqor5OoLfTXsFM2GUaWxHe3OIrbEjg9iV5BDFDF2quvmqMWL2Qr24jDYwCW/jFXHzpo3XxVF6OrdVb9VTqTgwdARbPmQogdnV68UwkiaVaOKKQsHqBkKhm+9WZj5GsCVDrL0t00zA4ccSflzggw9jAdif3YAS5Wefe3sya2zjfns720s1sgvEwAAJ60uRctukK5f9BrlsAxWdzCUJltCYQG5R3cJYsejV7fP2YbuAb/D9OF5Y0a/4XdPJ7DvZR821rOrZWEoc7ebkSPHgzGqCifAvAEp1ujExoLFgVu6Hj4JxOEUzAOGAatIA2qnN9eNfyuNlR1rdNViKlJO2r6m9EWPmVaFKyuz8ivJoMkOSTlSysfqreK7ThLYOl6xVdv7qbfXz9P3rLiknKrbfSVFlfXNOl3s/mUB0aT1piE9dH5bOUo3PTyKYdzaBQj2/UOWa4AtdHqbh0vK3H1vq4h2sdKxRru5RSZ7uwdnjn2GL3dHNZb1E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
